### ISSUE TITLE
Glazewm-extra doesn't start

### ISSUE THREAD

**Issue by itsme-microcip** [ptazithos/glazewm-extra#6]
Windows version: windows 11 Pro 22H2

glazewm-extra.toml conf:
`[[window_rules]]
command = "set title false"
match_process_name = ".*"`

glazewm conf:
https://github.com/FedeP14/conf/blob/master/glazewm/config.yaml

running with powershell or running with the double click on the exe file result in no output and the program doesn't start

**Comment by ptazithos** [comment]
Hi, could you give me more information so I can check this?

First, I want to make sure all the dependencies installed ([Webview2](https://developer.microsoft.com/en-us/microsoft-edge/webview2) and [VCRuntime140](https://www.microsoft.com/en-us/download/details.aspx?id=48145))

Second, I need the version of glazewm-extra. If you install it by scoop, run' scoop list'.
<img width="902" alt="Screenshot 2024-07-23 201512" src="https://github.com/user-attachments/assets/e5db6a2d-3e11-458e-b19e-c84b6a178888">

**Comment by itsme-microcip** [comment]
glaze-wm extra version is v0.1.7 like yours, i think th problem is some bug in my system with webview2 that my pc seems not support (i highly doubt it, but probably a debloat on my end caused it)

**Comment by ptazithos** [comment]
I am working on removing webview2 from the dependencies. I hope that works for you.
It still needs a week to complete. I linked the branch [remove-tauri](https://github.com/ptazithos/glazewm-extra/tree/refactor/remove-tauri) to this issue so you can trace the progress.

**Comment by ptazithos** [comment]
I remove webview2 since v0.1.9. Could you please try it?
