### ISSUE TITLE
Glazewm-extra doesn't start

### ISSUE THREAD

**Issue by FlaweDev** [ptazithos/glazewm-extra#8]
When I try to open a file, it goes to the tray and then disappears. However, it remains visible in the task manager. In an attempt to find out the reason, I tried to compile a build in visual code. This is the error I get when starting:

Loaded 'C:\Users\Flawe\Downloads\glazewm-extra-main\glazewm-extra-main\target\debug\glazewm-extra.exe'. Symbols loaded.
Loaded 'C:\Windows\System32\ntdll.dll'.
Loaded 'C:\Windows\System32\kernel32.dll'.
Loaded 'C:\Windows\System32\KernelBase.dll'.
Loaded 'C:\Windows\System32\bcryptprimitives.dll'.
Loaded 'C:\Windows\System32\psapi.dll'.
Loaded 'C:\Windows\System32\user32.dll'.
Loaded 'C:\Windows\System32\win32u.dll'.
Loaded 'C:\Windows\System32\gdi32.dll'.
Loaded 'C:\Windows\System32\gdi32full.dll'.
Loaded 'C:\Windows\System32\msvcp_win.dll'.
Loaded 'C:\Windows\System32\ucrtbase.dll'.
Loaded 'C:\Windows\System32\shell32.dll'.
Loaded 'C:\Windows\System32\ole32.dll'.
Loaded 'C:\Windows\System32\combase.dll'.
Loaded 'C:\Windows\System32\rpcrt4.dll'.
Loaded 'C:\Windows\System32\dwmapi.dll'.
Loaded 'C:\Windows\System32\oleaut32.dll'.
Loaded 'C:\Windows\System32\bcrypt.dll'.
Loaded 'C:\Windows\System32\advapi32.dll'.
Loaded 'C:\Windows\System32\msvcrt.dll'.
Loaded 'C:\Windows\System32\sechost.dll'.
Loaded 'C:\Windows\System32\ws2_32.dll'.
Loaded 'C:\Windows\System32\vcruntime140.dll'.
Loaded 'C:\Windows\System32\cryptbase.dll'.
Loaded 'C:\Windows\System32\imm32.dll'.
Loaded 'C:\Windows\System32\windows.storage.dll'.
Loaded 'C:\Windows\System32\WinTypes.dll'.
Loaded 'C:\Windows\System32\SHCore.dll'.
Loaded 'C:\Windows\System32\shlwapi.dll'.
Loaded 'C:\Windows\System32\profapi.dll'.
Loaded 'C:\Windows\System32\uxtheme.dll'.
Loaded 'C:\Windows\System32\msctf.dll'.
2024-08-11T06:53:28.849985Z  INFO glazewm_extra::service: Init EffectService with config: AppConfig { window_rules: [WindowRule { command: (Set, Titlebar(false)), match_process_name: Some(".*"), match_class_name: None, match_title: None }, WindowRule { command: (Set, Rounded(false)), match_process_name: Some(".*"), match_class_name: None, match_title: None }], focused_window_rules: [WindowRule { command: (Set, Translucent(255)), match_process_name: Some(".*"), match_class_name: None, match_title: None }], unfocused_window_rules: [WindowRule { command: (Set, Translucent(220)), match_process_name: Some(".*"), match_class_name: None, match_title: None }] }
Loaded 'C:\Windows\System32\mswsock.dll'.
Loaded 'C:\Windows\System32\dnsapi.dll'.
Loaded 'C:\Windows\System32\IPHLPAPI.DLL'.
Loaded 'C:\Windows\System32\nsi.dll'.
Loaded 'C:\Windows\System32\rasadhlp.dll'.
Loaded 'C:\Windows\System32\FWPUCLNT.DLL'.
thread 'tokio-runtime-worker' panicked at src\ipc\command.rs:33:55:
called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a sequence", line: 1, column: 70)
stack backtrace:
Loaded 'C:\Windows\System32\dbghelp.dll'.
   0: std::panicking::begin_panic_handler
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:652
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\panicking.rs:72
   2: core::result::unwrap_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\result.rs:1679
   3: enum2$<core::result::Result<glazewm_extra::ipc::command::Payload,serde_json::error::Error> >::unwrap
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\result.rs:1102
   4: glazewm_extra::ipc::command::get_windows::async_fn$0
             at .\src\ipc\command.rs:33
   5: glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block$0
             at .\src\ipc\event.rs:36
   6: tokio::runtime::task::core::impl$6::poll::closure$0<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block_env$0>,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle,alloc::alloc::Global> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\core.rs:328
   7: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block_env$0> > > >::with_mut
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\loom\std\unsafe_cell.rs:16
   8: tokio::runtime::task::core::Core<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block_env$0>,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle,alloc::alloc::Global> >::poll<enum2$<glazewm_extra::ipc::event::impl$
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\core.rs:317
   9: tokio::runtime::task::harness::poll_future::closure$0<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block_env$0>,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle,alloc::alloc::Global> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\harness.rs:485
  10: core::panic::unwind_safe::impl$25::call_once<enum2$<core::task::poll::Poll<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > >,tokio::runtime::task::harness::poll_future::closure_env$0<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::asy
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\panic\unwind_safe.rs:272
  11: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block_env$0>,alloc::sync::Arc<tokio::runtime::scheduler::m
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\panicking.rs:559
  12: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$1<enum2$<glazewm_extra::tray::impl$1::listen::async_fn$0::async_block_env$1>,alloc::sync::Arc<tokio::runtime::scheduler::multi_
  13: std::panicking::try<enum2$<core::task::poll::Poll<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<enum2$<glazewm_extra::ipc::event::impl$1::liste
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\panicking.rs:523
  14: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block_env$0>,alloc::sync::Arc<tokio::runtime::scheduler::multi
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\panic.rs:149
  15: tokio::runtime::task::harness::poll_future<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block_env$0>,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle,alloc::alloc::Global> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\harness.rs:473
  16: tokio::runtime::task::harness::Harness<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block_env$0>,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle,alloc::alloc::Global> >::poll_inner<enum2$<glazewm_extra::ipc::
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\harness.rs:208
  17: tokio::runtime::task::harness::Harness<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block_env$0>,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle,alloc::alloc::Global> >::poll<enum2$<glazewm_extra::ipc::event:
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\harness.rs:153
  18: tokio::runtime::task::raw::poll<enum2$<glazewm_extra::ipc::event::impl$1::listen::async_fn$0::async_block_env$0>,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle,alloc::alloc::Global> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\raw.rs:271
  19: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\raw.rs:201
  20: tokio::runtime::task::LocalNotified<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle,alloc::alloc::Global> >::run<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle,alloc::alloc::Global> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\mod.rs:427
  21: tokio::runtime::scheduler::multi_thread::worker::impl$1::run_task::closure$0
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\worker.rs:594
  22: tokio::runtime::coop::with_budget
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\coop.rs:107
  23: tokio::runtime::coop::budget
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\coop.rs:73
  24: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\worker.rs:593
  25: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\worker.rs:544
  26: tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure$0
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\worker.rs:509
  27: tokio::runtime::context::scoped::Scoped<enum2$<tokio::runtime::scheduler::Context> >::set<enum2$<tokio::runtime::scheduler::Context>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0,tuple$<> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\context\scoped.rs:40
  28: tokio::runtime::context::set_scheduler::closure$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\context.rs:180
  29: std::thread::local::LocalKey<tokio::runtime::context::Context>::try_with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>,tuple$<
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\thread\local.rs:283
  30: std::thread::local::LocalKey<tokio::runtime::context::Context>::with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>,tuple$<> >
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\thread\local.rs:260
  31: tokio::runtime::context::set_scheduler<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\context.rs:180
  32: tokio::runtime::scheduler::multi_thread::worker::run::closure$0
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\worker.rs:504
  33: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::worker::run::closure_env$0,tuple$<> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\context\runtime.rs:65
  34: tokio::runtime::scheduler::multi_thread::worker::run
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\worker.rs:496
  35: tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure$0
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\worker.rs:462
  36: tokio::runtime::blocking::task::impl$2::poll<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0,tuple$<> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\blocking\task.rs:42
  37: tokio::runtime::task::core::impl$6::poll::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\core.rs:328
  38: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0> > > >::with_mut
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\loom\std\unsafe_cell.rs:16
  39: tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task::Blocki
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\core.rs:317
  40: tokio::runtime::task::harness::poll_future::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\harness.rs:485
  41: core::panic::unwind_safe::impl$25::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\panic\unwind_safe.rs:272
  42: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,t
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\panicking.rs:559
  43: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$1<tokio::runtime::blocking::task::BlockingTask<tokio::net::addr::impl$17::to_socket_addrs::closure_env$0>,tokio::runtime::block
  44: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\panicking.rs:523
  45: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\panic.rs:149
  46: tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\harness.rs:473
  47: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll_inner<tokio::runtime::blocking::
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\harness.rs:208
  48: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task::
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\harness.rs:153
  49: tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\raw.rs:271
  50: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\raw.rs:201
  51: tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::BlockingSchedule>::run<tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\task\mod.rs:464
  52: tokio::runtime::blocking::pool::Task::run
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\blocking\pool.rs:160
  53: tokio::runtime::blocking::pool::Inner::run
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\blocking\pool.rs:518
  54: tokio::runtime::blocking::pool::impl$6::spawn_thread::closure$0
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\blocking\pool.rs:476
  55: core::hint::black_box
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\hint.rs:338
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Exception thrown at 0x00007FF8DA15F39C in glazewm-extra.exe: Microsoft C++ exception:  ?? ::st_panic at memory location 0x000000AAC81FB978.
2024-08-11T06:53:33.100695Z ERROR glazewm_extra::service: IPC error: Err(task 16 panicked

Stack backtrace:
   0: std::backtrace_rs::backtrace::dbghelp64::trace
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2: std::backtrace::Backtrace::create
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\backtrace.rs:331
   3: std::backtrace::Backtrace::capture
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\backtrace.rs:296
   4: anyhow::error::impl$1::from<tokio::runtime::task::error::JoinError>
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\anyhow-1.0.86\src\backtrace.rs:27
   5: core::result::impl$27::from_residual<tuple$<>,tokio::runtime::task::error::JoinError,anyhow::Error>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\result.rs:1989
   6: glazewm_extra::ipc::event::impl$1::listen::async_fn$0
             at .\src\ipc\event.rs:46
   7: glazewm_extra::service::impl$0::serve::async_fn$0::closure$0<glazewm_extra::ipc::event::IPCEventRegistry,glazewm_extra::tray::TrayEventRegistry>
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\macros\select.rs:557
   8: tokio::future::poll_fn::impl$1::poll<enum2$<glazewm_extra::service::impl$0::serve::async_fn$0::__tokio_select_util::Out<enum2$<core::result::Result<tuple$<>,anyhow::Error> >,enum2$<core::result::Result<tuple$<>,anyhow::Error> >,enum2$<core::result::Result<
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\future\poll_fn.rs:58
   9: glazewm_extra::service::impl$0::serve::async_fn$0<glazewm_extra::ipc::event::IPCEventRegistry,glazewm_extra::tray::TrayEventRegistry>
             at .\src\service.rs:119
  10: glazewm_extra::main::async_block$0
             at .\src\main.rs:34
  11: tokio::runtime::park::impl$4::block_on::closure$0<enum2$<glazewm_extra::main::async_block_env$0> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\park.rs:281
  12: tokio::runtime::coop::with_budget
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\coop.rs:107
  13: tokio::runtime::coop::budget
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\coop.rs:73
  14: tokio::runtime::park::CachedParkThread::block_on<enum2$<glazewm_extra::main::async_block_env$0> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\park.rs:281
  15: tokio::runtime::context::blocking::BlockingRegionGuard::block_on<enum2$<glazewm_extra::main::async_block_env$0> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\context\blocking.rs:66
  16: tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure$0<enum2$<glazewm_extra::main::async_block_env$0> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\mod.rs:87
  17: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure_env$0<enum2$<glazewm_extra::main::async_block_env$0> >,tuple$<> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\context\runtime.rs:65
  18: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<glazewm_extra::main::async_block_env$0> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\scheduler\multi_thread\mod.rs:86
  19: tokio::runtime::runtime::Runtime::block_on_inner<enum2$<glazewm_extra::main::async_block_env$0> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\runtime.rs:363
  20: tokio::runtime::runtime::Runtime::block_on<enum2$<glazewm_extra::main::async_block_env$0> >
             at C:\Users\Flawe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.39.2\src\runtime\runtime.rs:335
  21: glazewm_extra::main
             at .\src\main.rs:34
  22: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\ops\function.rs:250
  23: core::hint::black_box
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\core\src\hint.rs:338
  24: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\sys_common\backtrace.rs:155
  25: std::rt::lang_start::closure$0<tuple$<> >
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\rt.rs:159
  26: std::rt::lang_start_internal
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\rt.rs:141
  27: std::rt::lang_start<tuple$<> >
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23\library\std\src\rt.rs:158
  28: main
  29: invoke_main
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  30: __scrt_common_main_seh
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  31: BaseThreadInitThunk
  32: RtlUserThreadStart)
Unloaded 'C:\Windows\System32\FWPUCLNT.DLL'.
Loaded 'C:\Windows\System32\kernel.appcore.dll'.
The program '[16556] glazewm-extra.exe' has exited with code 0 (0x0).

Windows version: windows 11 Pro 23H2

**Comment by ptazithos** [comment]
Thanks for the feedback. 
According to the crack logs, I can see a panic at ipc/command.rs at line 33. The code was trying to get all managed windows from glazewm ipc server, but failed.
```rust
pub async fn get_windows() -> Result<Payload> {
    let res = command("windows").await?;
    let payload: Payload = serde_json::from_str(&res).unwrap();
    Ok(payload)
}
```
May I know your glazewm version?

**Comment by FlaweDev** [comment]
I have never worked with rust, however I will try to help in any way

GlazeWM version: 3.1.1
[config.txt](https://github.com/user-attachments/files/16573558/config.txt)

**Comment by ptazithos** [comment]
Currently, glazewm-extra only works with GlazeWM v2.
There are several breaking changes to the ipc server that I haven't handled in GlazeWM v3. 

For your case, you are blocked by the [windows command](https://github.com/glzr-io/glazewm-js/blob/b4c265cc8879999c2f0e516ce87cf3bcb670e269/src/client.ts#L82)
The windows request used to be `windows`, but it is `query windows` right now.

**Comment by FlaweDev** [comment]
It's a pity. I'll take a look at the code in hopes that I can fix this, but I'm not sure.
So I look forward to future updates. Thank you
